export * from './summoner.resource';
export * from './base.resource';
export * from './league.resource';
export * from './match.resource';
export * from './account.resource';
export * from './championmastery.resource';
export * from './champion.resource';
export * from './clash.resource';
export * from './leagueexp.resource';
